### ISSUE TITLE
Improvement: QA componentの位置が下がっていく in __NOTO__

### ISSUE THREAD

**Issue by ItsukiKigoshi** [kanawha-st/SaigaiAId#31]
### Problem
質問に答えていくことでQAコンポーネント（掲載画像の赤丸部分）の位置が下がってしまう．回答していく際にスクロールする必要があり，不便．
<img width="834" alt="image" src="https://github.com/kanawha-st/SaigaiAid/assets/67095865/ab509147-7133-49ab-a9d1-f07b1e731a64">

### Solution
1. Vuetifyの[Slide Groups](https://vuetifyjs.com/en/components/slide-groups/#usage)を用いることで，答えた質問を横スクロールで表示する
1. QA Componentが画面の中心になるように自動的にサイトがスクロールされるようにする（技術的な可否は分かりません...）

### P.S.
はじめまして，Code for Japan Slackの"#proj-noto-support-info"に入っている大学生の木越と申します．
Feedbackをこちらに投稿するのが適切かどうか分かりませんが，気づいたことを書かせていただきました．
今後ともどうぞよろしくお願い致します．

**Comment by kanawha-st** [comment]
フィードバックありがとうございます！
Solutionの提案までしていただいて感謝です。
画面のPDF取り込み機能があるので、横スクロールより、自動スクロールの方が簡単と判断しました。
こちらです↓
https://github.com/kanawha-st/SaigaiAid/commit/99ce4a0ff5d95d97ceca2290b0b0f0cc224b9cdd

**Comment by ItsukiKigoshi** [comment]
早速ご対応いただきありがとうございます！
Vueにこのような機能があったとは知らず勉強になりました．
